set(_CATKIN_CURRENT_PACKAGE "nav_tests")
set(nav_tests_VERSION "0.0.0")
set(nav_tests_MAINTAINER "developer <developer@todo.todo>")
set(nav_tests_PACKAGE_FORMAT "2")
set(nav_tests_BUILD_DEPENDS "rospy")
set(nav_tests_BUILD_EXPORT_DEPENDS "rospy")
set(nav_tests_BUILDTOOL_DEPENDS "catkin")
set(nav_tests_BUILDTOOL_EXPORT_DEPENDS )
set(nav_tests_EXEC_DEPENDS "rospy")
set(nav_tests_RUN_DEPENDS "rospy")
set(nav_tests_TEST_DEPENDS )
set(nav_tests_DOC_DEPENDS )
set(nav_tests_URL_WEBSITE "")
set(nav_tests_URL_BUGTRACKER "")
set(nav_tests_URL_REPOSITORY "")
set(nav_tests_DEPRECATED "")