set(_CATKIN_CURRENT_PACKAGE "hsrb_common_config")
set(hsrb_common_config_VERSION "1.0.0")
set(hsrb_common_config_MAINTAINER "HSR Support <xr-hsr-support@mail.toyota.co.jp>")
set(hsrb_common_config_PACKAGE_FORMAT "1")
set(hsrb_common_config_BUILD_DEPENDS )
set(hsrb_common_config_BUILD_EXPORT_DEPENDS )
set(hsrb_common_config_BUILDTOOL_DEPENDS "catkin")
set(hsrb_common_config_BUILDTOOL_EXPORT_DEPENDS )
set(hsrb_common_config_EXEC_DEPENDS )
set(hsrb_common_config_RUN_DEPENDS )
set(hsrb_common_config_TEST_DEPENDS )
set(hsrb_common_config_DOC_DEPENDS )
set(hsrb_common_config_URL_WEBSITE "")
set(hsrb_common_config_URL_BUGTRACKER "")
set(hsrb_common_config_URL_REPOSITORY "")
set(hsrb_common_config_DEPRECATED "")