set(_CATKIN_CURRENT_PACKAGE "hsrb_rosnav_config")
set(hsrb_rosnav_config_VERSION "1.0.0")
set(hsrb_rosnav_config_MAINTAINER "HSR Support <xr-hsr-support@mail.toyota.co.jp>")
set(hsrb_rosnav_config_PACKAGE_FORMAT "2")
set(hsrb_rosnav_config_BUILD_DEPENDS "amcl" "dwa_local_planner" "map_server" "move_base" "robot_state_publisher" "hsrb_description" "gazebo_ros" "controller_manager" "tf" "joint_state_publisher" "tmc_odometry_switcher")
set(hsrb_rosnav_config_BUILD_EXPORT_DEPENDS "amcl" "dwa_local_planner" "map_server" "move_base" "robot_state_publisher" "hsrb_description" "gazebo_ros" "controller_manager" "tf" "joint_state_publisher" "tmc_odometry_switcher")
set(hsrb_rosnav_config_BUILDTOOL_DEPENDS "catkin")
set(hsrb_rosnav_config_BUILDTOOL_EXPORT_DEPENDS )
set(hsrb_rosnav_config_EXEC_DEPENDS "amcl" "dwa_local_planner" "map_server" "move_base" "robot_state_publisher" "hsrb_description" "gazebo_ros" "controller_manager" "tf" "joint_state_publisher" "tmc_odometry_switcher")
set(hsrb_rosnav_config_RUN_DEPENDS "amcl" "dwa_local_planner" "map_server" "move_base" "robot_state_publisher" "hsrb_description" "gazebo_ros" "controller_manager" "tf" "joint_state_publisher" "tmc_odometry_switcher")
set(hsrb_rosnav_config_TEST_DEPENDS "roslaunch" "rostest" "tmc_gazebo_worlds" "rviz" "joint_state_publisher" "controller_manager" "hsrb_common_config" "hsrb_gazebo_bringup" "tf")
set(hsrb_rosnav_config_DOC_DEPENDS )
set(hsrb_rosnav_config_URL_WEBSITE "")
set(hsrb_rosnav_config_URL_BUGTRACKER "")
set(hsrb_rosnav_config_URL_REPOSITORY "")
set(hsrb_rosnav_config_DEPRECATED "")