#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/developer/workspace/devel_isolated/octomap_server:/home/developer/workspace/devel_isolated/navros_pkg:/home/developer/workspace/devel_isolated/nav_tests:/home/developer/workspace/devel_isolated/manipulation:/home/developer/workspace/devel_isolated/hsrb_rosnav_config:/home/developer/workspace/devel_isolated/hsrb_rosnav:/home/developer/workspace/devel_isolated/hsrb_moveit_config:/home/developer/workspace/devel_isolated/hsrb_mapping:/home/developer/workspace/devel_isolated/hsrb_gazebo_bringup:/home/developer/workspace/devel_isolated/hsrb_description:/home/developer/workspace/devel_isolated/hsrb_common_config:/home/developer/workspace/devel_isolated/cv:/home/developer/workspace/devel:/opt/ros/melodic:/home/developer/workspace/devel_isolated/dynamic_edt_3d:/home/developer/workspace/devel_isolated/octomap'
export LD_LIBRARY_PATH='/home/developer/workspace/devel_isolated/navros_pkg/lib:/home/developer/workspace/devel_isolated/nav_tests/lib:/home/developer/workspace/devel_isolated/manipulation/lib:/home/developer/workspace/devel_isolated/hsrb_rosnav_config/lib:/home/developer/workspace/devel_isolated/hsrb_moveit_config/lib:/home/developer/workspace/devel_isolated/hsrb_mapping/lib:/home/developer/workspace/devel_isolated/hsrb_gazebo_bringup/lib:/home/developer/workspace/devel_isolated/hsrb_description/lib:/home/developer/workspace/devel_isolated/hsrb_common_config/lib:/home/developer/workspace/devel_isolated/cv/lib:/home/developer/workspace/devel/lib:/opt/ros/melodic/lib:/home/developer/workspace/devel_isolated/dynamic_edt_3d/lib:/home/developer/workspace/devel_isolated/dynamic_edt_3d/lib/x86_64-linux-gnu:/home/developer/workspace/devel_isolated/octomap/lib:/home/developer/workspace/devel_isolated/octomap/lib/x86_64-linux-gnu'
export PATH='/opt/ros/melodic/bin:/home/developer/workspace/devel_isolated/dynamic_edt_3d/bin:/home/developer/workspace/devel_isolated/octomap/bin:/additional_software/jason/build/scripts:/home/developer/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/developer/.fzf/bin'
export PKG_CONFIG_PATH='/home/developer/workspace/devel_isolated/navros_pkg/lib/pkgconfig:/home/developer/workspace/devel_isolated/nav_tests/lib/pkgconfig:/home/developer/workspace/devel_isolated/manipulation/lib/pkgconfig:/home/developer/workspace/devel_isolated/hsrb_rosnav_config/lib/pkgconfig:/home/developer/workspace/devel_isolated/hsrb_moveit_config/lib/pkgconfig:/home/developer/workspace/devel_isolated/hsrb_mapping/lib/pkgconfig:/home/developer/workspace/devel_isolated/hsrb_gazebo_bringup/lib/pkgconfig:/home/developer/workspace/devel_isolated/hsrb_description/lib/pkgconfig:/home/developer/workspace/devel_isolated/hsrb_common_config/lib/pkgconfig:/home/developer/workspace/devel_isolated/cv/lib/pkgconfig:/home/developer/workspace/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig:/home/developer/workspace/devel_isolated/dynamic_edt_3d/lib/pkgconfig:/home/developer/workspace/devel_isolated/dynamic_edt_3d/lib/x86_64-linux-gnu/pkgconfig:/home/developer/workspace/devel_isolated/octomap/lib/pkgconfig:/home/developer/workspace/devel_isolated/octomap/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/developer/workspace/devel_isolated/cv/lib/python2.7/dist-packages:/home/developer/workspace/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/developer/workspace/devel_isolated/dynamic_edt_3d/lib/python2.7/dist-packages:/home/developer/workspace/devel_isolated/octomap/lib/python2.7/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/developer/workspace/devel_isolated/octomap_server/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/developer/workspace/src/manip/octomap_server:$ROS_PACKAGE_PATH"