set(_CATKIN_CURRENT_PACKAGE "cv")
set(cv_VERSION "0.0.0")
set(cv_MAINTAINER "developer <developer@todo.todo>")
set(cv_PACKAGE_FORMAT "2")
set(cv_BUILD_DEPENDS "rospy" "std_msgs" "message_generation")
set(cv_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "message_runtime")
set(cv_BUILDTOOL_DEPENDS "catkin")
set(cv_BUILDTOOL_EXPORT_DEPENDS )
set(cv_EXEC_DEPENDS "rospy" "std_msgs" "message_runtime")
set(cv_RUN_DEPENDS "rospy" "std_msgs" "message_runtime")
set(cv_TEST_DEPENDS )
set(cv_DOC_DEPENDS )
set(cv_URL_WEBSITE "")
set(cv_URL_BUGTRACKER "")
set(cv_URL_REPOSITORY "")
set(cv_DEPRECATED "")