# CMake generated Testfile for 
# Source directory: /home/developer/workspace/src/manip/hsrb_rosnav/hsrb_rosnav_config
# Build directory: /workspace/build_isolated/hsrb_rosnav_config
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_hsrb_rosnav_config_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_hsrb_nav.launch "/workspace/build_isolated/hsrb_rosnav_config/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_hsrb_nav.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_hsrb_nav.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_rosnav_config/launch/hsrb_nav.launch\" ")
add_test(_ctest_hsrb_rosnav_config_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_simple_gazebo_world.launch "/workspace/build_isolated/hsrb_rosnav_config/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_simple_gazebo_world.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_simple_gazebo_world.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_rosnav_config/launch/simple_gazebo_world.launch\" ")
add_test(_ctest_hsrb_rosnav_config_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_test_gazebo_world.launch "/workspace/build_isolated/hsrb_rosnav_config/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_test_gazebo_world.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_rosnav_config_launch_test_gazebo_world.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_rosnav_config/launch/test_gazebo_world.launch\" ")
add_test(_ctest_hsrb_rosnav_config_rostest_test_hsrb_navigation.test "/workspace/build_isolated/hsrb_rosnav_config/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_rosnav_config/test_results/hsrb_rosnav_config/rostest-test_hsrb_navigation.xml" "--return-code" "/usr/bin/python2 /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_rosnav_config --package=hsrb_rosnav_config --results-filename test_hsrb_navigation.xml --results-base-dir \"/workspace/build_isolated/hsrb_rosnav_config/test_results\" /home/developer/workspace/src/manip/hsrb_rosnav/hsrb_rosnav_config/test/hsrb_navigation.test ")
subdirs("gtest")
