set(_CATKIN_CURRENT_PACKAGE "hsrb_gazebo_bringup")
set(hsrb_gazebo_bringup_VERSION "1.0.0")
set(hsrb_gazebo_bringup_MAINTAINER "HSR Support <xr-hsr-support@mail.toyota.co.jp>")
set(hsrb_gazebo_bringup_PACKAGE_FORMAT "1")
set(hsrb_gazebo_bringup_BUILD_DEPENDS )
set(hsrb_gazebo_bringup_BUILD_EXPORT_DEPENDS )
set(hsrb_gazebo_bringup_BUILDTOOL_DEPENDS "catkin")
set(hsrb_gazebo_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(hsrb_gazebo_bringup_EXEC_DEPENDS )
set(hsrb_gazebo_bringup_RUN_DEPENDS )
set(hsrb_gazebo_bringup_TEST_DEPENDS "roslaunch")
set(hsrb_gazebo_bringup_DOC_DEPENDS )
set(hsrb_gazebo_bringup_URL_WEBSITE "")
set(hsrb_gazebo_bringup_URL_BUGTRACKER "")
set(hsrb_gazebo_bringup_URL_REPOSITORY "")
set(hsrb_gazebo_bringup_DEPRECATED "")