set(_CATKIN_CURRENT_PACKAGE "hsrb_mapping")
set(hsrb_mapping_VERSION "1.0.0")
set(hsrb_mapping_MAINTAINER "HSR Support <xr-hsr-support@mail.toyota.co.jp>")
set(hsrb_mapping_PACKAGE_FORMAT "2")
set(hsrb_mapping_BUILD_DEPENDS "gmapping" "hector_mapping" "map_server" "slam_karto")
set(hsrb_mapping_BUILD_EXPORT_DEPENDS "gmapping" "hector_mapping" "map_server" "slam_karto")
set(hsrb_mapping_BUILDTOOL_DEPENDS "catkin")
set(hsrb_mapping_BUILDTOOL_EXPORT_DEPENDS )
set(hsrb_mapping_EXEC_DEPENDS "rviz" "joy" "teleop_twist_keyboard" "teleop_twist_joy" "gmapping" "hector_mapping" "map_server" "slam_karto")
set(hsrb_mapping_RUN_DEPENDS "rviz" "joy" "teleop_twist_keyboard" "teleop_twist_joy" "gmapping" "hector_mapping" "map_server" "slam_karto")
set(hsrb_mapping_TEST_DEPENDS "roslaunch" "rostest" "roslint" "imagemagick" "tmc_gazebo_worlds" "rviz" "joint_state_publisher" "controller_manager" "hsrb_common_config" "hsrb_gazebo_bringup" "tf")
set(hsrb_mapping_DOC_DEPENDS )
set(hsrb_mapping_URL_WEBSITE "")
set(hsrb_mapping_URL_BUGTRACKER "")
set(hsrb_mapping_URL_REPOSITORY "")
set(hsrb_mapping_DEPRECATED "")