set(_CATKIN_CURRENT_PACKAGE "hsrb_rosnav")
set(hsrb_rosnav_VERSION "1.0.0")
set(hsrb_rosnav_MAINTAINER "HSR Support <xr-hsr-support@mail.toyota.co.jp>")
set(hsrb_rosnav_PACKAGE_FORMAT "1")
set(hsrb_rosnav_BUILD_DEPENDS )
set(hsrb_rosnav_BUILD_EXPORT_DEPENDS "hsrb_mapping" "hsrb_rosnav_config")
set(hsrb_rosnav_BUILDTOOL_DEPENDS "catkin")
set(hsrb_rosnav_BUILDTOOL_EXPORT_DEPENDS )
set(hsrb_rosnav_EXEC_DEPENDS "hsrb_mapping" "hsrb_rosnav_config")
set(hsrb_rosnav_RUN_DEPENDS "hsrb_mapping" "hsrb_rosnav_config")
set(hsrb_rosnav_TEST_DEPENDS )
set(hsrb_rosnav_DOC_DEPENDS )
set(hsrb_rosnav_URL_WEBSITE "")
set(hsrb_rosnav_URL_BUGTRACKER "")
set(hsrb_rosnav_URL_REPOSITORY "")
set(hsrb_rosnav_DEPRECATED "")