# CMake generated Testfile for 
# Source directory: /home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping
# Build directory: /workspace/build_isolated/hsrb_mapping
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_hsrb_mapping_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_gmapping.launch "/workspace/build_isolated/hsrb_mapping/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_gmapping.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_gmapping.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping/launch/gmapping.launch\" ")
add_test(_ctest_hsrb_mapping_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_hector.launch "/workspace/build_isolated/hsrb_mapping/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_hector.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_hector.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping/launch/hector.launch\" ")
add_test(_ctest_hsrb_mapping_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_karto.launch "/workspace/build_isolated/hsrb_mapping/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_karto.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_karto.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping/launch/karto.launch\" ")
add_test(_ctest_hsrb_mapping_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_rviz.launch "/workspace/build_isolated/hsrb_mapping/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_rviz.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_rviz.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping/launch/rviz.launch\" ")
add_test(_ctest_hsrb_mapping_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_teleop_joy.launch "/workspace/build_isolated/hsrb_mapping/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_teleop_joy.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_teleop_joy.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping/launch/teleop_joy.launch\" ")
add_test(_ctest_hsrb_mapping_roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_teleop_keyboard.launch "/workspace/build_isolated/hsrb_mapping/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_teleop_keyboard.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/roslaunch-check__home_developer_workspace_src_manip_hsrb_rosnav_hsrb_mapping_launch_teleop_keyboard.launch.xml\" \"/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping/launch/teleop_keyboard.launch\" ")
add_test(_ctest_hsrb_mapping_rostest_test_hsrb_mapping.test "/workspace/build_isolated/hsrb_mapping/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/workspace/build_isolated/hsrb_mapping/test_results/hsrb_mapping/rostest-test_hsrb_mapping.xml" "--return-code" "/usr/bin/python2 /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping --package=hsrb_mapping --results-filename test_hsrb_mapping.xml --results-base-dir \"/workspace/build_isolated/hsrb_mapping/test_results\" /home/developer/workspace/src/manip/hsrb_rosnav/hsrb_mapping/test/hsrb_mapping.test ")
subdirs("gtest")
