set(_CATKIN_CURRENT_PACKAGE "hsrb_description")
set(hsrb_description_VERSION "1.0.0")
set(hsrb_description_MAINTAINER "HSR Support <xr-hsr-support@mail.toyota.co.jp>")
set(hsrb_description_PACKAGE_FORMAT "1")
set(hsrb_description_BUILD_DEPENDS "xacro" "rosbash" "hsrb_meshes")
set(hsrb_description_BUILD_EXPORT_DEPENDS "xacro" "rviz" "hsrb_meshes")
set(hsrb_description_BUILDTOOL_DEPENDS "catkin")
set(hsrb_description_BUILDTOOL_EXPORT_DEPENDS )
set(hsrb_description_EXEC_DEPENDS "xacro" "rviz" "hsrb_meshes")
set(hsrb_description_RUN_DEPENDS "xacro" "rviz" "hsrb_meshes")
set(hsrb_description_TEST_DEPENDS "liburdfdom-tools" "urdfdom_py" "robot_state_publisher" "joint_state_publisher" "roslaunch")
set(hsrb_description_DOC_DEPENDS )
set(hsrb_description_URL_WEBSITE "None")
set(hsrb_description_URL_BUGTRACKER "")
set(hsrb_description_URL_REPOSITORY "")
set(hsrb_description_DEPRECATED "")